languageCode = "en-US"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Home"
copyright = "&copy; 2026 Wamli"

[params]
  dateFormat = "2 January 2006"

  description = "A clean, elegant Hugo theme for content-focused websites"

  [params.author]
    name = "Christoph Brewing"
    image = "img/author.jpg"
    headline = "Welcome"
    bio = ""
